spring:
  application:
    name: mf-service-menu
 
#Tomcat Embedded Server Configuration
server: 
  port: 24209
    servlet:    context-path: /mf-service-menu
 
#Eureka Configuration Properties  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka