spring:
  application:    name: mf-gateway
    
server:  port: 7000
  
zuul:  routes:    serv-jpa-platos:
        path: //mf-jpa-platos/**/**
        serviceId: mf-jpa-platos
    serv-jpa-menu:
        path: //mf-jpa-menu/**/**
        serviceId: mf-jpa-menu
    serv-jpa-ingrediente:
        path: //mf-jpa-ingrediente/**/**
        serviceId: mf-jpa-ingrediente
    serv-jpa-receta:
        path: //mf-jpa-receta/**/**
        serviceId: mf-jpa-receta
 
#Eureka Configuration Properties
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      